name: Reddit - InkWisps

on:
  schedule:
    - cron: '0 4 * * *'    # 09:30 AM IST  
    - cron: '45 6 * * *'   # 11:15 AM IST  
    - cron: '15 8 * * *'   # 01:45 PM IST  
    - cron: '0 10 * * *'   # 03:30 PM IST  
    - cron: '30 13 * * *'  # 06:00 PM IST  
    - cron: '15 16 * * *'  # 09:45 PM IST  
    - cron: '0 17 * * *'   # 10:30 PM IST  
    - cron: '30 19 * * *'  # 01:00 AM IST (next day)

  workflow_dispatch:

jobs:
  reddit_post:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_REFRESH_TOKEN: ${{ secrets.REDDIT_REFRESH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ffmpeg (static binary, fast)
        run: |
          curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz
          cd ffmpeg-*-amd64-static
          sudo mv ffmpeg ffprobe /usr/local/bin
          cd ..
          rm -rf ffmpeg*

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install praw dropbox requests python-telegram-bot moviepy opencv-python ffmpeg-python pytz

      - name: Run Reddit Bot
        run: python "reddit.py"
